env:
  browser: true
  es2021: true
extends: standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: true
rules:
  padding-line-between-statements:
    [error, { blankLine: always, prev: '*', next: '*' }]
  comma-dangle: off
  '@typescript-eslint/comma-dangle': off
